# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "ecs-project-terraform-state-647647556952-eu-west-2"
    encrypt      = true
    key          = "./terraform.tfstate"
    region       = "eu-west-2"
    use_lockfile = true
  }
}
